package com.brasajava.view.tpv;

import com.brasajava.model.Cuenta;
import com.brasajava.model.Factura;
import com.brasajava.util.ApplicationLocale;
import com.brasajava.util.interfaces.Internationalizable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.springframework.context.ApplicationContext;
import org.springframework.context.MessageSource;

/**
 * Esta clase representa la búsqueda de factura.
 * @author Ricardo Maximino
 */
public class BuscaFactura extends javax.swing.JDialog implements Internationalizable {

    private final ApplicationContext context;
    private final MessageSource messageSource;
    private final ApplicationLocale applicationLocale;
    private String str;
    private List<Factura> lista;

    private TPV tpv;

    /**
     * El único constructor para crear una instancia desta clase.
     *
     * @param tpv del tipo com.brasajava.view.tpv.TPV.
     * @param context del tipo org.springframework.context.ApplicationContext.
     * <p>Utilizando el context se pedirá una instancia de las clase:</p>
     * <ul>
     * <li>org.springframework.context.MessageSource</li>
     * <li>com.brasajava.util.ApplicationLocale</li>
     * </ul>
     * lista = new ArrayList&lt;&gt;();
     */
    public BuscaFactura(TPV tpv, ApplicationContext context) {
        super(tpv, true);
        this.tpv = tpv;
        this.context = context;
        this.messageSource = context.getBean(MessageSource.class);
        this.applicationLocale = context.getBean(ApplicationLocale.class);
        lista = new ArrayList<>();
        initComponents();
        setWithInternationalization();
    }

    /**
     * Retorna el valor de la variable lista.
     * @return  del tipo java.util.List&lt;Factura&gt;.
     */
    public List<Factura> getLista() {
        return lista;
    }

    /**
     * Configura el valor de la variable lista.
     * @param lista del tipo java.util.List&lt;Factura&gt;.
     */
    public void setLista(List<Factura> lista) {
        this.lista = lista;
        setModelData();
    }

    /**
     * Actualiza toda la interfaz gráfica con el idioma seleccionado en la
     * instacia única de la clase
     * com.brasajava.util.ApplicationLocale.getLocale().
     */
    @Override
    public void refreshLanguage() {
        setWithInternationalization();
        ((FacturaTableModel) tabla.getModel()).refreshLanguage();
        ((FacturaTableModel) tabla.getModel()).fireTableStructureChanged();
    }
    
    /**
     * Permite otras clases accionar la funcion de filtro programaticamente.
     * @param fecha del tipo java.lang.String.
     * <p>La fecha obligatoriamente tiene que estar en el formato dd/MM/yyyy</p>
     */
    public void setTxtFecha(String fecha){
        txtFecha.setText(str);
        porFecha();
    }
    
    private void setModelData() {
        FacturaTableModel model = (FacturaTableModel) tabla.getModel();
        model.getListaDeFactura().addAll(lista);
        model.fireTableDataChanged();
    }

    private void setWithInternationalization() {
        lblFecha.setText(messageSource.getMessage("DATE", null, applicationLocale.getLocale()));
        btnBuscar.setText(messageSource.getMessage("button_Search", null, applicationLocale.getLocale()));
    }

    private FacturaTableModel getModel() {
        return context.getBean(FacturaTableModel.class);
    }

    private void porFecha() {
        String[] arrayDate = txtFecha.getText().split("/");
        //
        LocalDate fecha = null;
        try {
            if(arrayDate.length == 3){
                fecha = LocalDate.of(Integer.parseInt(arrayDate[2]), Integer.parseInt(arrayDate[1]), Integer.parseInt(arrayDate[0]));
            }else{
                throw new Exception();
            }
        } catch (Exception ex) {
            txtFecha.setText("");
        }

        FacturaTableModel model = (FacturaTableModel) tabla.getModel();
        model.getListaDeFactura().clear();
        if (txtFecha.getText().isEmpty()) {
            model.getListaDeFactura().addAll(lista);
        } else {
            for (Factura f : lista) {
                if (f.getFecha().equals(fecha)){
                    model.getListaDeFactura().add(f);
                }
            }
        }
        model.fireTableDataChanged();

    }

    private void clear() {
        txtFecha.setText("");
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panelControles = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        scrollTabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 372));

        panel.setPreferredSize(new java.awt.Dimension(650, 350));

        panelControles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFecha.setText("FECHA");

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(205, 205, 205))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabla.setModel(getModel());
        tabla.setRowHeight(40);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(30);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(30);
        tabla.getColumnModel().getColumn(3).setPreferredWidth(40);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        scrollTabla.setViewportView(tabla);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTabla))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        porFecha();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Factura f;
        if (evt.getClickCount() == 2) {
            FacturaTableModel model = (FacturaTableModel) tabla.getModel();
            f = model.getListaDeFactura().get(tabla.getSelectedRow());
            Cuenta c =  f.getCuentas().get(0);
            c.setReabrir(true);
            //para no confundir las cuentas 
            c.setNombre(c.getId() + " - " + System.currentTimeMillis());
            //para facturas con una sola cuenta.
            tpv.abrirCuenta(f.getCuentas().get(0));
            dispose();
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
       if(evt.getKeyCode()== 10){
           porFecha();
       }
       if(txtFecha.getText().isEmpty()){
           porFecha();
       }
    }//GEN-LAST:event_txtFechaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelControles;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
