/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brasajava.view.tpv;

import com.brasajava.model.Cuenta;
import com.brasajava.model.Factura;
import com.brasajava.model.Persona;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class Pagar extends javax.swing.JDialog {

    private boolean noPagaRapito;
    private boolean cobrado;
    private final Cuenta cuenta;
    private final Factura factura;
    private final Persona cliente;
    private final Persona usuario;
    private BigDecimal entregado;
    private BigDecimal cambio;
    private final TPV tpv;

    /**
     * Creates new form Pagar
     *
     * @param parent
     * @param cuenta
     * @param cliente
     * @param usuario
     * @param tpvModel
     */
    public Pagar(java.awt.Frame parent, Cuenta cuenta, Persona cliente, Persona usuario,TPV tpv) {
        super(parent, true);
        initComponents();
        this.cuenta = cuenta;
        this.cliente = cliente;
        this.usuario = usuario;
        this.tpv = tpv;
        noPagaRapito = false;
        factura = new Factura();
        prepara();
        activarCartera();
    }
    @Override
    public void dispose(){
        if(!cobrado){
            tpv.abrirCuenta(cuenta);
        }  
        super.dispose();
    }

    private void prepara() {
        lblTotal.setText(cuenta.getTotal().toString());
        lblEntregado.setText(cuenta.getTotal().toString());
        lblCambio.setText(cuenta.getTotal().toString());
    }

    private void activarCartera() {
        for (Component c : panelCartera.getComponents()) {
            JButton b = (JButton)c;
                    if(b.getActionCommand().equals("dinero")){
                        b.addActionListener(this::carteraAction);
                    }                  
        }
    }
    private void carteraAction(ActionEvent e){
        JButton b = (JButton) e.getSource();
        if(noPagaRapito){
            entregado = entregado.add(new BigDecimal(b.getName()));
            hacerCuentas();
        }else{
            entregado = new BigDecimal(b.getName());
            noPagaRapito = true;
            hacerCuentas();
        }
    }
 
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblEntregado = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        panelCartera = new javax.swing.JPanel();
        btn50Euros = new javax.swing.JButton();
        btn20Euros = new javax.swing.JButton();
        btn10Euros = new javax.swing.JButton();
        btn5Euros = new javax.swing.JButton();
        btn2Euros = new javax.swing.JButton();
        btn10Centimos = new javax.swing.JButton();
        btn1Euro = new javax.swing.JButton();
        btn5Centimos = new javax.swing.JButton();
        btn50Centimos = new javax.swing.JButton();
        btn2Centimos = new javax.swing.JButton();
        btn20Centimos = new javax.swing.JButton();
        btn1Centimo = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(this.getClass().getResource("/images/icon.png")).getImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TOTAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CAMBIO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ENTREGADO");

        lblCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCambio.setText("0,00");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("15,00");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblEntregado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEntregado.setText("15,00");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEntregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnOk});

        panelCartera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btn50Euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cincuentaEuros.png"))); // NOI18N
        btn50Euros.setActionCommand("dinero");
        btn50Euros.setName("50.00"); // NOI18N
        btn50Euros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn50EurosKeyPressed(evt);
            }
        });

        btn20Euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vinteEuros.png"))); // NOI18N
        btn20Euros.setActionCommand("dinero");
        btn20Euros.setName("20.00"); // NOI18N

        btn10Euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diezEuros.png"))); // NOI18N
        btn10Euros.setActionCommand("dinero");
        btn10Euros.setName("10.00"); // NOI18N

        btn5Euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cincoEuros.png"))); // NOI18N
        btn5Euros.setActionCommand("dinero");
        btn5Euros.setName("5.00"); // NOI18N

        btn2Euros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dosEuros.png"))); // NOI18N
        btn2Euros.setActionCommand("dinero");
        btn2Euros.setBorder(null);
        btn2Euros.setName("2.00"); // NOI18N
        btn2Euros.setPreferredSize(new java.awt.Dimension(70, 70));

        btn10Centimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diezCentimo.png"))); // NOI18N
        btn10Centimos.setActionCommand("dinero");
        btn10Centimos.setName("0.10"); // NOI18N
        btn10Centimos.setPreferredSize(new java.awt.Dimension(70, 70));

        btn1Euro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unEuro.png"))); // NOI18N
        btn1Euro.setActionCommand("dinero");
        btn1Euro.setBorderPainted(false);
        btn1Euro.setName("1.00"); // NOI18N
        btn1Euro.setPreferredSize(new java.awt.Dimension(70, 70));

        btn5Centimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cincoCentimo.png"))); // NOI18N
        btn5Centimos.setActionCommand("dinero");
        btn5Centimos.setName("0.05"); // NOI18N
        btn5Centimos.setPreferredSize(new java.awt.Dimension(70, 70));

        btn50Centimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cincuentaCentimos.png"))); // NOI18N
        btn50Centimos.setActionCommand("dinero");
        btn50Centimos.setName("0.50"); // NOI18N
        btn50Centimos.setPreferredSize(new java.awt.Dimension(70, 70));

        btn2Centimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dosCentimos.png"))); // NOI18N
        btn2Centimos.setActionCommand("dinero");
        btn2Centimos.setName("0.02"); // NOI18N
        btn2Centimos.setPreferredSize(new java.awt.Dimension(70, 70));

        btn20Centimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vinteCentimos.png"))); // NOI18N
        btn20Centimos.setActionCommand("dinero");
        btn20Centimos.setName("0.20"); // NOI18N
        btn20Centimos.setPreferredSize(new java.awt.Dimension(70, 70));

        btn1Centimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unCentimo.png"))); // NOI18N
        btn1Centimo.setActionCommand("dinero");
        btn1Centimo.setName("0.01"); // NOI18N
        btn1Centimo.setPreferredSize(new java.awt.Dimension(70, 70));

        btnCE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCarteraLayout = new javax.swing.GroupLayout(panelCartera);
        panelCartera.setLayout(panelCarteraLayout);
        panelCarteraLayout.setHorizontalGroup(
            panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarteraLayout.createSequentialGroup()
                .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn50Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20Euros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10Euros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5Euros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCarteraLayout.createSequentialGroup()
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCarteraLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn2Euros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn10Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCarteraLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btn1Euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarteraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarteraLayout.createSequentialGroup()
                                .addComponent(btn20Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn1Centimo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarteraLayout.createSequentialGroup()
                                .addComponent(btn50Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn2Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        panelCarteraLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn10Centimos, btn1Centimo, btn1Euro, btn20Centimos, btn2Centimos, btn2Euros, btn50Centimos, btn5Centimos});

        panelCarteraLayout.setVerticalGroup(
            panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarteraLayout.createSequentialGroup()
                .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCarteraLayout.createSequentialGroup()
                        .addComponent(btn50Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn20Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn5Euros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarteraLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2Euros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn10Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn5Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1Euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn2Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn50Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCarteraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn20Centimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1Centimo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCarteraLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn10Centimos, btn1Centimo, btn1Euro, btn20Centimos, btn2Centimos, btn2Euros, btn50Centimos, btn5Centimos});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelCartera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCartera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        entregado = new BigDecimal("0.00");
        entregado.setScale(2, RoundingMode.HALF_DOWN);
        hacerCuentas();
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        entregado = new BigDecimal(lblEntregado.getText());
        entregado.setScale(2, RoundingMode.HALF_DOWN);
        cambio = entregado.subtract(cuenta.getTotal());
        if (cambio.doubleValue() >= 0) {
            cuenta.setCobrada(true);
            factura.setCobrada(true);
            factura.setCliente(cliente);
            factura.setUsuario(usuario);
            factura.setTotal(cuenta.getTotal());
            factura.getCuentas().add(cuenta);

            //guardar no BD

            //imprimir

            tpv.crearCuenta();
            cobrado = true;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Falta dinero.");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btn50EurosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn50EurosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn50EurosKeyPressed

    private void hacerCuentas(){
        cambio = entregado.subtract(cuenta.getTotal());
        lblEntregado.setText(entregado.toString());
        lblCambio.setText(cambio.toString());
    }

    private void esc(KeyEvent evt){
        JOptionPane.showMessageDialog(this, evt.getKeyCode() + "");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10Centimos;
    private javax.swing.JButton btn10Euros;
    private javax.swing.JButton btn1Centimo;
    private javax.swing.JButton btn1Euro;
    private javax.swing.JButton btn20Centimos;
    private javax.swing.JButton btn20Euros;
    private javax.swing.JButton btn2Centimos;
    private javax.swing.JButton btn2Euros;
    private javax.swing.JButton btn50Centimos;
    private javax.swing.JButton btn50Euros;
    private javax.swing.JButton btn5Centimos;
    private javax.swing.JButton btn5Euros;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblEntregado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelCartera;
    // End of variables declaration//GEN-END:variables
}
