/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brasajava.view.producto;

import com.brasajava.model.Grupo;
import com.brasajava.model.Producto;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author Ricardo
 */
public class ProductoGrupo extends javax.swing.JInternalFrame {

    private Producto producto;
    private Grupo grupo;
    private DefaultListModel<Grupo> listModel;
    private ApplicationContext context;

    /**
     * Creates new form ProductoGrupo
     * @param context
     */
    public ProductoGrupo(ApplicationContext context) {
        this.context = context;
        initComponents();
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
        setProductoFields();
    }

    private void setProductoFields() {
        lblCodigoProductoValue.setText(producto.getId() + "");
        txtNombreProducto.setText(producto.getNombre());
        txtDescripcionProducto.setText(producto.getDescripcion());
        txtCustoDelProducto.setText(producto.getCusto().toString());
        txtMargen.setText(producto.getMargen() + "");
        txtPrecioSinIva.setText(producto.getPrecioSinIva().toString());
        txtIva.setText(producto.getIva() + "");
        txtPrecioMasIva.setText(producto.getPrecioMasIva().toString());
        txtAlmacen.setText(producto.getAlmacen() + "");

        for (Grupo g : producto.getGrupos()) {
            listModel.addElement(g);
        }

        if (producto.getImage() != null && !producto.getImage().isEmpty()) {
            Image image = new ImageIcon(getClass().getResource("/images/" + producto.getImage())).getImage().getScaledInstance(190, 170, Image.SCALE_SMOOTH);
            lblMolduraProducto.setIcon(new ImageIcon(image));
        }
    }

    private DefaultListModel<Grupo> getListModel() {
        DefaultListModel<Grupo> model = new DefaultListModel<>();
        listModel = model;
        return model;
    }
    private ProductoTableModel getTableModel(){
        return new ProductoTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        panelProducto = new javax.swing.JPanel();
        lblCodigoProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblDescripcionDelProducto = new javax.swing.JLabel();
        lblCustoDelProducto = new javax.swing.JLabel();
        lblPrecioSinIva = new javax.swing.JLabel();
        lblPrecioConIva = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblAlmacen = new javax.swing.JLabel();
        lblGruposProducto = new javax.swing.JLabel();
        lblImagenProducto = new javax.swing.JLabel();
        lblMolduraProducto = new javax.swing.JLabel();
        lblCodigoProductoValue = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtDescripcionProducto = new javax.swing.JTextField();
        txtCustoDelProducto = new javax.swing.JTextField();
        txtPrecioSinIva = new javax.swing.JTextField();
        txtPrecioMasIva = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtAlmacen = new javax.swing.JTextField();
        lblMargenDelProducto = new javax.swing.JLabel();
        txtMargen = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCancelarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        scrollList = new javax.swing.JScrollPane();
        listProducto = new javax.swing.JList<>();
        panelGrupo = new javax.swing.JPanel();
        lblCodigoGrupo = new javax.swing.JLabel();
        lblNombreGrupo = new javax.swing.JLabel();
        lblDescripcionGrupo = new javax.swing.JLabel();
        lblCodigoGrupoValue = new javax.swing.JLabel();
        txtNombreGrupo = new javax.swing.JTextField();
        txtDescripcionGrupo = new javax.swing.JTextField();
        lblImageGrupo = new javax.swing.JLabel();
        lblMolduraGrupo = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaParaPruductoGrupo = new javax.swing.JTable();
        btnCancelarGrupo = new javax.swing.JButton();
        btnNuevoGrupo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lblCodigoProducto.setText("COD.");

        lblNombreProducto.setText("NOMBRE");

        lblDescripcionDelProducto.setText("DESCRIPCION");

        lblCustoDelProducto.setText("CUSTO DEL PROD.");

        lblPrecioSinIva.setText("PRECIO SIN I.V.A.");

        lblPrecioConIva.setText("PRECIO CON I.V.A.");

        lblIva.setText("I.V.A.");

        lblAlmacen.setText("ALMACEN");

        lblGruposProducto.setText("GRUPOS");

        lblImagenProducto.setText("IMAGEN");

        lblMolduraProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.awt.Image image = new javax.swing.ImageIcon(getClass().getResource("/images/hitPina.png")).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        lblMolduraProducto.setText("IMAGEN");
        lblMolduraProducto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMolduraProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblMolduraProducto.setPreferredSize(new java.awt.Dimension(200, 200));

        lblCodigoProductoValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigoProductoValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCustoDelProducto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtPrecioSinIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtPrecioMasIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtAlmacen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblMargenDelProducto.setText("MARGEN");

        txtMargen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("%");

        jLabel15.setText("%");

        btnCancelarProducto.setText("CANCELAR");
        btnCancelarProducto.setVisible(false);

        btnNuevoProducto.setText("NUEVO");

        listProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listProducto.setModel(getListModel());
        scrollList.setViewportView(listProducto);

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoProducto)
                            .addComponent(lblNombreProducto)
                            .addComponent(lblDescripcionDelProducto)
                            .addComponent(lblCustoDelProducto)
                            .addComponent(lblPrecioSinIva)
                            .addComponent(lblPrecioConIva))
                        .addGap(25, 25, 25)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPrecioMasIva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(txtPrecioSinIva, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustoDelProducto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProductoLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAlmacen)
                                            .addComponent(lblIva)
                                            .addComponent(lblMargenDelProducto))
                                        .addGap(48, 48, 48)
                                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIva)
                                            .addComponent(txtMargen)))
                                    .addGroup(panelProductoLayout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(txtAlmacen))))
                            .addComponent(txtDescripcionProducto)
                            .addComponent(txtNombreProducto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGruposProducto)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(lblCodigoProductoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnCancelarProducto))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(scrollList, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblImagenProducto))
                            .addGroup(panelProductoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblMolduraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(241, 241, 241))
        );

        panelProductoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarProducto, btnNuevoProducto});

        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoProducto)
                        .addComponent(lblCodigoProductoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelarProducto)
                        .addComponent(btnNuevoProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionDelProducto)
                    .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustoDelProducto)
                    .addComponent(txtCustoDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMargen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(lblMargenDelProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioSinIva)
                    .addComponent(txtPrecioSinIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(lblIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioConIva)
                    .addComponent(txtPrecioMasIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlmacen)
                    .addComponent(txtAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(lblGruposProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollList))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(lblImagenProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMolduraProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Producto", panelProducto);

        lblCodigoGrupo.setText("COD.");

        lblNombreGrupo.setText("NOMBRE");

        lblDescripcionGrupo.setText("DESCRIPCION");

        lblCodigoGrupoValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigoGrupoValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImageGrupo.setText("IMAGEN");

        lblMolduraGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMolduraGrupo.setText("IMAGEN");
        lblMolduraGrupo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMolduraGrupo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaParaPruductoGrupo.setModel(getTableModel());
        scrollTabla.setViewportView(tablaParaPruductoGrupo);

        btnCancelarGrupo.setText("CANCELAR");

        btnNuevoGrupo.setText("NUEVO");

        javax.swing.GroupLayout panelGrupoLayout = new javax.swing.GroupLayout(panelGrupo);
        panelGrupo.setLayout(panelGrupoLayout);
        panelGrupoLayout.setHorizontalGroup(
            panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrupoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrupoLayout.createSequentialGroup()
                        .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoGrupoValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGrupoLayout.createSequentialGroup()
                                .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreGrupo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoGrupo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelGrupoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblDescripcionGrupo)
                                        .addComponent(txtNombreGrupo)
                                        .addComponent(txtDescripcionGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGrupoLayout.createSequentialGroup()
                                        .addComponent(btnCancelarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(btnNuevoGrupo)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrupoLayout.createSequentialGroup()
                                .addComponent(lblMolduraGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGrupoLayout.createSequentialGroup()
                                .addComponent(lblImageGrupo)
                                .addGap(96, 96, 96))))))
        );

        panelGrupoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarGrupo, btnNuevoGrupo});

        panelGrupoLayout.setVerticalGroup(
            panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageGrupo)
                    .addComponent(btnCancelarGrupo)
                    .addComponent(btnNuevoGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrupoLayout.createSequentialGroup()
                        .addComponent(lblCodigoGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodigoGrupoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(lblNombreGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcionGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcionGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMolduraGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Grupo", panelGrupo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarGrupo;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnNuevoGrupo;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblCodigoGrupo;
    private javax.swing.JLabel lblCodigoGrupoValue;
    private javax.swing.JLabel lblCodigoProducto;
    private javax.swing.JLabel lblCodigoProductoValue;
    private javax.swing.JLabel lblCustoDelProducto;
    private javax.swing.JLabel lblDescripcionDelProducto;
    private javax.swing.JLabel lblDescripcionGrupo;
    private javax.swing.JLabel lblGruposProducto;
    private javax.swing.JLabel lblImageGrupo;
    private javax.swing.JLabel lblImagenProducto;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblMargenDelProducto;
    private javax.swing.JLabel lblMolduraGrupo;
    private javax.swing.JLabel lblMolduraProducto;
    private javax.swing.JLabel lblNombreGrupo;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecioConIva;
    private javax.swing.JLabel lblPrecioSinIva;
    private javax.swing.JList<Grupo> listProducto;
    private javax.swing.JPanel panelGrupo;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JScrollPane scrollList;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaParaPruductoGrupo;
    private javax.swing.JTextField txtAlmacen;
    private javax.swing.JTextField txtCustoDelProducto;
    private javax.swing.JTextField txtDescripcionGrupo;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtMargen;
    private javax.swing.JTextField txtNombreGrupo;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioMasIva;
    private javax.swing.JTextField txtPrecioSinIva;
    // End of variables declaration//GEN-END:variables
}
